
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 145
#define YY_END_OF_BUFFER 146
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[498] =
    {   0,
        0,    0,    0,    0,  146,  144,  143,  143,   28,  144,
      144,   15,   16,   21,   20,   10,   19,   33,   22,    1,
        1,   13,    6,   24,    7,   25,   29,  136,  136,   30,
       31,   14,   17,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,   11,   34,   12,  140,  140,  143,  142,
      142,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  137,    0,  137,   35,
      141,   18,   32,    3,  138,    3,    1,    0,    0,    0,
        1,    5,    8,   26,   23,   27,    9,  136,  136,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      131,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  101,  136,  136,   58,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  105,  136,   96,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      139,  142,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  135,  137,    0,  141,    0,    0,
        3,    0,    1,    1,  136,  136,  136,   95,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,   41,  136,

      136,  136,   85,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,   80,  136,   91,   93,   94,  136,
      136,  108,  136,  136,   89,  136,   69,  136,  136,  136,
       84,  136,  136,  136,  136,  136,  136,  136,   78,  136,
      136,  136,   81,  136,  136,  136,  136,  136,  136,  136,
      136,  136,   79,  136,  136,   97,  142,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    3,    0,
        0,    0,    3,  136,  136,  136,  136,  136,   44,  104,
       57,  136,  136,  136,  103,  136,  125,   62,  136,  136,
      136,  136,  136,  109,  136,  136,  136,  136,  136,  136,

      136,   46,  136,   90,   63,   88,   92,  106,  136,  110,
      114,  136,  136,   72,  136,   37,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  102,
      136,  136,   82,   42,  136,  136,  136,  136,   70,  136,
      100,  142,    0,    0,    0,    0,    0,    0,    0,    3,
      136,  136,  136,  136,  136,   66,   64,  136,  132,  119,
       83,  127,  136,   60,  111,  123,  136,  136,  136,  136,
       47,   48,   49,  136,  136,  115,  120,   87,  136,  136,
      136,   67,  136,  136,  136,  136,  136,  136,  136,  136,
      128,  136,   86,  136,  136,  136,  136,   51,  136,  136,

      133,   74,  142,    0,    4,  136,  136,  136,   76,  136,
      136,  136,  136,  136,  124,  136,  136,  136,  136,  136,
      136,  136,  136,  136,   40,  136,  130,  136,  136,   65,
       45,  136,  136,  136,   52,   53,   54,  129,  136,  142,
      136,  136,  136,  136,   68,  107,   55,   56,  136,  136,
      136,  121,   61,  112,   59,   38,   39,  122,   73,   98,
      136,  134,  136,  136,    0,  136,   36,  118,  136,   71,
      136,   43,  113,  116,  136,  136,   50,    0,    0,    0,
      136,  136,  126,   77,  117,  136,   99,    0,  136,  136,
      136,    2,   75,    0,    0,  142,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    5,    6,    7,    5,    5,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   25,   26,   27,   28,
       29,   30,    5,   31,   32,   32,   32,   32,   33,   32,
       34,   35,   36,   35,   35,   35,   35,   37,   35,   35,
       35,   38,   35,   39,   35,   35,   35,   35,   35,   35,
       40,   41,   42,   43,   44,    5,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   54,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    4,    3,    3,
        3,    5,    3,    5,    3,    3,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    3,    3,    3,    3,    3,
        3,    7,    8,    9,    9,    9,    9,    9,    9,    3,
        3,    3,    3,   10,    7,    7,    7,    7,    8,    7,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    3,
        3,    3
    } ;

static const flex_int16_t yy_base[512] =
    {   0,
        0,    0,  798,  797,  807,  810,   71,   74,  746,   68,
      132,  810,  810,  810,  798,  810,   74,   97,  793,  190,
      201,  777,  810,   57,  810,   60,  810,    0,  765,  810,
      810,  810,    0,   45,  742,   49,   34,  172,  186,  736,
      190,  204,  206,   36,   73,   65,  750,  207,  220,   53,
      753,  181,  738,  810,  810,  810,  810,  780,  274,    0,
      734,  787,  786,  785,  784,  254,  783,  239,  782,  730,
      234,  728,  725,  732,  725,  775,  774,  219,  773,  810,
        0,  810,  810,  210,  810,  241,  285,  296,  274,    0,
      307,  810,  810,  810,  810,  810,  810,    0,  741,  717,

      715,  729,  714,  712,  715,  711,  727,  712,  712,  719,
        0,  706,  714,  216,  717,  709,  696,  705,  199,  706,
      703,  715,    0,  699,  234,    0,   70,  695,  698,  695,
      233,  696,  278,  693,  705,  286,  695,    0,  702,    0,
      703,  286,  703,  281,  690,  696,  697,  700,  686,  687,
      693,  684,  278,  680,  681,  291,  677,  688,  673,  674,
      810,  689,  726,  725,  724,  682,  671,  667,  294,  668,
      678,  718,  667,  662,  810,  714,    0,    0,  344,  671,
      315,  348,  281,    0,  687,  656,  665,    0,  653,  657,
      659,  665,  652,  665,  649,  665,  287,  646,    0,  651,

      646,  644,    0,  660,  641,  658,  654,  654,  639,  640,
      635,  343,  649,  633,    0,  632,    0,    0,    0,  633,
      644,  315,  645,  640,    0,  641,  682,  639,  629,  631,
        0,  620,  638,  627,  288,  618,  632,  618,  621,  631,
      614,  629,    0,  617,  625,  615,  623,  622,  607,  620,
      615,  614,    0,  177,  614,    0,  614,  657,  615,  655,
      654,  653,  598,  651,  608,  649,    0,  352,  365,  371,
      366,  378,  393,  621,  593,  588,  595,  594,    0,    0,
        0,  595,  586,  584,    0,  597,    0,    0,  578,  596,
      588,  580,  579,  229,  578,  595,  578,  585,  614,  617,

      614,    0,  583,    0,    0,  626,    0,    0,  573,    0,
      578,  578,  580,    0,  567,    0,  582,  581,  576,  571,
      578,  565,  560,  559,  560,  569,  564,  567,  563,    0,
      552,  551,    0,    0,  401,  550,  560,  554,    0,  560,
        0,  551,  600,  599,  543,  596,  584,  581,  409,  421,
      568,  555,  554,  549,  552,    0,    0,  540,    0,    0,
        0,    0,  546,  384,    0,  541,  540,  534,  528,  545,
        0,    0,    0,  540,  532,    0,    0,    0,  534,  535,
      522,    0,  537,  522,  533,  523,  518,  518,  530,  532,
        0,  515,    0,  515,  527,  529,  524,    0,  481,  475,

        0,    0,  481,  496,  810,  464,  454,  437,    0,  436,
      435,  439,  477,  472,    0,  433,  426,  439,  431,  425,
      437,  437,  434,  433,    0,  417,    0,  417,  429,    0,
        0,  421,  415,  414,    0,    0,    0,    0,  423,  467,
      426,  406,  419,  408,    0,    0,    0,    0,  408,  415,
      414,    0,    0,  340,    0,    0,    0,    0,    0,  454,
      406,    0,  396,  409,  404,  153,    0,    0,  398,    0,
      406,    0,    0,  352,  310,  308,    0,  416,  419,  431,
      429,  284,    0,    0,    0,  263,    0,  432,  218,  111,
       81,    0,    0,  446,  447,  450,  810,  504,  509,  514,

      521,  531,  536,  541,  546,  549,  553,  555,  556,  560,
      564
    } ;

static const flex_int16_t yy_def[512] =
    {   0,
      497,    1,  498,  498,  497,  497,  497,  497,  499,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  500,  500,  497,
      497,  497,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  497,  497,  497,  497,  497,  497,  499,
      499,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  501,  497,  501,  497,
      502,  497,  497,  503,  497,  504,  497,  497,  497,  505,
      497,  497,  497,  497,  497,  497,  497,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      497,  499,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  501,  506,  502,  507,  497,
      504,  508,  497,  505,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  499,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  509,  497,  497,  497,
      510,  497,  497,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  499,  497,  497,  497,  497,  497,  497,  497,  497,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  499,  497,  497,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  499,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  511,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  511,  511,  511,
      500,  500,  500,  500,  500,  500,  500,  511,  500,  500,
      500,  500,  500,  511,  511,  511,    0,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497
    } ;

static const flex_int16_t yy_nxt[883] =
    {   0,
        6,    7,    8,    7,    6,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   22,   23,   24,   25,   26,
       27,   28,   28,   28,   28,   29,   28,   28,   28,   30,
        6,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   28,   41,   28,   28,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   28,   28,   54,
       55,   56,   59,   59,   59,   59,   59,   59,   62,   63,
       80,   64,  110,   65,   93,   94,   95,   81,   96,   97,
      100,  101,  111,  106,  136,   66,   67,   68,   69,  137,

      107,  492,  102,   82,  108,  155,  103,  109,  104,  141,
      156,   83,   70,   84,   84,   84,   84,   84,   84,   84,
       84,   84,  138,   71,   72,  142,   73,  213,  143,  492,
       74,  214,  139,  140,   75,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   77,   77,   77,   77,   77,   77,   77,
       77,   76,   78,   76,   76,   79,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   76,   76,   76,   86,  481,   87,   87,   87,   87,
       87,   87,   87,   88,   88,   86,  482,   91,   91,   91,
       91,   91,   91,   91,   91,   91,  175,  112,  113,  114,
      116,  117,  158,  159,  339,   89,  115,  340,  118,  123,
      492,  119,  179,  205,  120,   80,  124,  125,  127,  121,
      133,  126,  128,  180,  134,  145,   90,  206,  179,  146,
       80,  129,  130,  199,  135,  131,  147,  165,  150,  148,
      132,  151,  152,  182,  149,   59,   59,   59,  167,  200,
      153,  365,  163,  164,  180,  177,  211,  154,  218,  182,
      183,  183,  168,  219,  366,  169,  212,  183,  183,   86,

      170,   87,   87,   87,   87,   87,   87,   87,   88,   88,
       86,  493,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   86,  246,   91,   91,   91,   91,   91,   91,   91,
       91,   91,  221,  226,  231,  285,  481,  222,  232,  286,
      223,  247,  235,  236,  233,  237,  250,  271,  227,  261,
      321,  322,  251,  252,  262,  268,  487,  268,  180,  272,
      299,  272,  300,  271,  309,  301,  302,  310,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  349,  486,  349,
      311,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      347,  303,  473,  348,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  413,  485,  474,  414,  478,  180,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  395,  478,
      396,  488,  478,  397,  398,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  478,  478,  180,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  489,  480,  490,  478,
      478,  491,  492,  478,  484,  483,  477,  476,  475,  480,
       80,  472,  480,  471,  180,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  480,  480,  461,  460,  459,  458,
      494,  457,  456,  455,  454,  453,  452,  451,  450,  480,
      480,  449,  448,  480,  496,  447,  446,  445,  444,  443,

      442,  441,   80,  495,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   60,   60,   60,   60,   60,   98,
       98,   98,   98,   98,  176,  440,  176,  176,  176,  176,
      176,  178,  439,  178,  178,  178,  178,  178,  178,  178,
      178,   84,  438,   84,  437,   84,  181,  436,  181,  435,
      181,  184,  184,  184,  267,  267,  267,  269,  269,  273,
      273,  346,  346,  346,  350,  350,  479,  479,  479,  479,
      479,  479,  479,  479,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  412,  411,  410,  409,  408,  407,

      406,  405,  405,  175,  404,   80,   80,  403,  402,  401,
      400,  399,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,   80,  374,  373,  372,  371,  370,  369,  368,
      367,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,   80,  345,   80,  344,   80,
       80,   80,  343,   80,  342,  341,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  320,  319,  318,  317,  316,  315,   80,  314,
      313,  312,  308,  307,  306,  305,  304,  298,  297,  296,

      295,  294,  293,  292,  291,  290,  289,  288,  287,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      270,  497,  266,  265,   80,  264,  263,  260,  259,  258,
       80,   80,   80,  257,  256,  255,  254,  253,  249,  248,
      245,  244,  243,  242,  241,  240,  239,  238,  234,  230,
      229,  228,  225,  224,  220,  217,  216,  215,  210,  209,
      208,  207,  204,  203,  202,  201,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      175,  175,  175,  174,  173,  172,  171,  166,   80,   80,
       80,   80,   80,   80,  162,  161,  160,  157,  144,  122,

      105,   99,   92,   85,   80,   61,  497,   58,   58,    5,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497
    } ;

static const flex_int16_t yy_chk[883] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    7,    8,    8,    8,   10,   10,
       17,   10,   37,   10,   24,   24,   24,   17,   26,   26,
       34,   34,   37,   36,   44,   10,   10,   10,   10,   44,

       36,  491,   34,   17,   36,   50,   34,   36,   34,   46,
       50,   18,   10,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   45,   10,   10,   46,   10,  127,   46,  490,
       10,  127,   45,   45,   10,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   20,  466,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   21,  466,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   78,   38,   38,   38,
       39,   39,   52,   52,  254,   20,   38,  254,   39,   41,
      489,   39,   84,  119,   39,   68,   41,   41,   42,   39,
       43,   41,   42,   84,   43,   48,   20,  119,   84,   48,
       66,   42,   42,  114,   43,   42,   48,   68,   49,   48,
       42,   49,   49,   86,   48,   59,   59,   59,   71,  114,
       49,  294,   66,   66,   86,   78,  125,   49,  131,   86,
       89,   89,   71,  131,  294,   71,  125,  183,  183,   87,

       71,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       88,  486,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   91,  153,   91,   91,   91,   91,   91,   91,   91,
       91,   91,  133,  136,  142,  197,  482,  133,  142,  197,
      133,  153,  144,  144,  142,  144,  156,  181,  136,  169,
      235,  235,  156,  156,  169,  179,  476,  179,  181,  182,
      212,  182,  212,  181,  222,  212,  212,  222,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  271,  475,  271,
      222,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      270,  212,  454,  270,  272,  272,  272,  272,  272,  272,

      272,  272,  272,  364,  474,  454,  364,  465,  269,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  335,  478,
      335,  478,  479,  335,  335,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  480,  488,  273,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  481,  465,  481,  494,
      495,  481,  481,  496,  471,  469,  464,  463,  461,  478,
      460,  451,  479,  450,  350,  449,  444,  443,  442,  441,
      440,  439,  434,  433,  480,  488,  432,  429,  428,  426,
      488,  424,  423,  422,  421,  420,  419,  418,  417,  494,
      495,  416,  414,  496,  495,  413,  412,  411,  410,  408,

      407,  406,  404,  494,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  499,  499,  499,  499,  499,  500,
      500,  500,  500,  500,  501,  403,  501,  501,  501,  501,
      501,  502,  400,  502,  502,  502,  502,  502,  502,  502,
      502,  503,  399,  503,  397,  503,  504,  396,  504,  395,
      504,  505,  505,  505,  506,  506,  506,  507,  507,  508,
      508,  509,  509,  509,  510,  510,  511,  511,  511,  511,
      511,  511,  511,  511,  394,  392,  390,  389,  388,  387,
      386,  385,  384,  383,  381,  380,  379,  375,  374,  370,
      369,  368,  367,  366,  363,  358,  355,  354,  353,  352,

      351,  348,  347,  346,  345,  344,  343,  342,  340,  338,
      337,  336,  332,  331,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  315,  313,  312,
      311,  309,  306,  303,  301,  300,  299,  298,  297,  296,
      295,  293,  292,  291,  290,  289,  286,  284,  283,  282,
      278,  277,  276,  275,  274,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  255,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  242,  241,  240,  239,  238,
      237,  236,  234,  233,  232,  230,  229,  228,  227,  226,
      224,  223,  221,  220,  216,  214,  213,  211,  210,  209,

      208,  207,  206,  205,  204,  202,  201,  200,  198,  196,
      195,  194,  193,  192,  191,  190,  189,  187,  186,  185,
      180,  176,  174,  173,  172,  171,  170,  168,  167,  166,
      165,  164,  163,  162,  160,  159,  158,  157,  155,  154,
      152,  151,  150,  149,  148,  147,  146,  145,  143,  141,
      139,  137,  135,  134,  132,  130,  129,  128,  124,  122,
      121,  120,  118,  117,  116,  115,  113,  112,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       79,   77,   76,   75,   74,   73,   72,   70,   69,   67,
       65,   64,   63,   62,   61,   58,   53,   51,   47,   40,

       35,   29,   22,   19,   15,    9,    5,    4,    3,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scade.l"
#line 2 "scade.l"

#include "stdio.h"
#include "scade.tab.h"

#line 811 "lex.yy.c"

#line 813 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "scade.l"


#line 1034 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 498 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 810 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "scade.l"
{ return INTEGER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "scade.l"
{ return TYPED_INTEGER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "scade.l"
{ return FLOAT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "scade.l"
{ return TYPED_FLOAT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "scade.l"
{ return DOUBLE_COLON; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "scade.l"
{ return SEMICOLON; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "scade.l"
{ return EQUAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "scade.l"
{ return DOUBLE_LT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "scade.l"
{ return DOUBLE_GT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "scade.l"
{ return COMMA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "scade.l"
{ return L_BRACE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "scade.l"
{ return R_BRACE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "scade.l"
{ return COLON; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "scade.l"
{ return CARET; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "scade.l"
{ return L_PARENTHESE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "scade.l"
{ return R_PARENTHESE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "scade.l"
{ return UNDERSCORE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "scade.l"
{ return ARROW_TO_RIGHT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "scade.l"
{ return MINUS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "scade.l"
{ return PLUS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "scade.l"
{ return MUL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "scade.l"
{ return DIV; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "scade.l"
{ return DIFF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "scade.l"
{ return LT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "scade.l"
{ return GT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "scade.l"
{ return LE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "scade.l"
{ return GE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "scade.l"
{ return SHARP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "scade.l"
{ return CONCAT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "scade.l"
{ return L_S_BRACKET; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "scade.l"
{ return R_S_BRACKET; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "scade.l"
{ return DOUBLE_DOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "scade.l"
{ return DOT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "scade.l"
{ return VERTICAL_BAR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "scade.l"
{ return PREFIXOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "scade.l"
{ return ABSTRACT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "scade.l"
{ return OPEN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "scade.l"
{ return PACKAGE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "scade.l"
{ return PRIVATE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "scade.l"
{ return PUBLIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "scade.l"
{ return END; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "scade.l"
{ return TYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "scade.l"
{ return IMPORTED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "scade.l"
{ return BOOL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "scade.l"
{ return SIGNED; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "scade.l"
{ return INT8; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "scade.l"
{ return INT16; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "scade.l"
{ return INT32; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "scade.l"
{ return INT64; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "scade.l"
{ return UNSIGNED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "scade.l"
{ return UINT8; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "scade.l"
{ return UINT16; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "scade.l"
{ return UINT32; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "scade.l"
{ return UINT64; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "scade.l"
{ return FLOAT32; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "scade.l"
{ return FLOAT64; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "scade.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "scade.l"
{ return IS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "scade.l"
{ return NUMERIC; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "scade.l"
{ return FLOAT_SYM; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "scade.l"
{ return INTEGER_SYM; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 "scade.l"
{ return ENUM; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 "scade.l"
{ return LAST; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 "scade.l"
{ return CONST; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "scade.l"
{ return SENSOR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "scade.l"
{ return CLOCK; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "scade.l"
{ return PROBE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 118 "scade.l"
{ return DEFAULT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "scade.l"
{ return NOT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "scade.l"
{ return WHEN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "scade.l"
{ return FUNCTION; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "scade.l"
{ return NODE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "scade.l"
{ return RETURNS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "scade.l"
{ return WHERE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "scade.l"
{ return SPECIALIZE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "scade.l"
{ return ASSUME; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "scade.l"
{ return GUARANTEE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "scade.l"
{ return SIG; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "scade.l"
{ return VAR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "scade.l"
{ return LET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "scade.l"
{ return TEL; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "scade.l"
{ return TRUE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "scade.l"
{ return FALSE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 134 "scade.l"
{ return PRE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "scade.l"
{ return FBY; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "scade.l"
{ return TIMES; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 137 "scade.l"
{ return MERGE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 138 "scade.l"
{ return LNOT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 139 "scade.l"
{ return MOD; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 140 "scade.l"
{ return LAND; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 141 "scade.l"
{ return LOR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 142 "scade.l"
{ return LXOR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 143 "scade.l"
{ return LSL; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "scade.l"
{ return LSR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 145 "scade.l"
{ return AND; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 146 "scade.l"
{ return OR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 147 "scade.l"
{ return XOR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 148 "scade.l"
{ return REVERSE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 149 "scade.l"
{ return TRANSPOSE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 150 "scade.l"
{ return WITH; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 151 "scade.l"
{ return IF; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 152 "scade.l"
{ return THEN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 153 "scade.l"
{ return ELSE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 154 "scade.l"
{ return CASE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 155 "scade.l"
{ return OF; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 156 "scade.l"
{ return MAKE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 157 "scade.l"
{ return FLATTEN; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 158 "scade.l"
{ return MAP; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 159 "scade.l"
{ return FOLD; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 160 "scade.l"
{ return MAPI; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 161 "scade.l"
{ return FOLDI; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 162 "scade.l"
{ return MAPFOLD; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 163 "scade.l"
{ return MAPFOLDI; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 164 "scade.l"
{ return MAPW; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 165 "scade.l"
{ return MAPWI; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 166 "scade.l"
{ return MAPFOLDW; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 167 "scade.l"
{ return MAPFOLDWI; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 168 "scade.l"
{ return ACTIVATE; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 169 "scade.l"
{ return EVERY; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 170 "scade.l"
{ return MATCH; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 171 "scade.l"
{ return INITIAL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 172 "scade.l"
{ return RESTART; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 173 "scade.l"
{ return FOLDW; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 174 "scade.l"
{ return FOLDWI; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 175 "scade.l"
{ return EMIT; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 176 "scade.l"
{ return AUTOMATON; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 177 "scade.l"
{ return FINAL; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 178 "scade.l"
{ return STATE; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 179 "scade.l"
{ return UNLESS; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 180 "scade.l"
{ return RESUME; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 181 "scade.l"
{ return DO; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 182 "scade.l"
{ return ELSIF; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 183 "scade.l"
{ return UNTIL; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 184 "scade.l"
{ return SYNCHRO; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 187 "scade.l"
{ return CHAR; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 189 "scade.l"
{ 
    return ID;
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 193 "scade.l"
{ return NAME; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 195 "scade.l"
{ BEGIN(COMMENT); }
	YY_BREAK

case 139:
YY_RULE_SETUP
#line 197 "scade.l"
{ BEGIN(INITIAL); } 
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 198 "scade.l"

	YY_BREAK

case 141:
YY_RULE_SETUP
#line 201 "scade.l"
/* eat up single line comments */
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 203 "scade.l"
printf("PRAGMA: %s\n", yytext);
	YY_BREAK
case 143:
/* rule 143 can match eol */
YY_RULE_SETUP
#line 205 "scade.l"
/* eat up whitespace */
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 207 "scade.l"
printf("Unrecognized character: %s\n", yytext);
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 209 "scade.l"
ECHO;
	YY_BREAK
#line 1822 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 498 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 498 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 497);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 209 "scade.l"

